name: Optimize Images # Nombre del workflow

on:
  push:
    branches:
      - main # Se ejecuta cuando hay cambios en la rama "main"

jobs:
  optimize:
    runs-on: ubuntu-latest # Se ejecuta en un entorno Ubuntu

    steps:
      - name: Checkout repository # Descarga el código del repositorio
        uses: actions/checkout@v3

      - name: Optimize images # Paso para optimizar imágenes
        uses: docker://ghcr.io/imagemin/imagemin-cli:latest # Usa un contenedor Docker con herramientas de optimización
        with:
          args: '**/*.{jpg,jpeg,png,gif,svg} --out-dir=./' # Comprime imágenes en los formatos más comunes

      - name: Commit optimized images # Paso para confirmar y subir los cambios optimizados
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Optimized images" || echo "No changes to commit"
          git push

