name: Optimize Images

on:
  push:
    branches:
      - main

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install image optimization tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jpegoptim optipng gifsicle

      - name: Optimize images
        run: |
          find . -type f -name "*.jpg" -exec jpegoptim --max=80 --strip-all {} \;
          find . -type f -name "*.png" -exec optipng -o7 {} \;
          find . -type f -name "*.gif" -exec gifsicle -O3 --lossy=80 -b {} \;

      - name: Commit optimized images
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Optimized images" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
