name: Optimize Images # Nombre del workflow

on:
  push:
    branches:
      - main # Se ejecuta cuando hay cambios en la rama "main"

jobs:
  optimize:
    runs-on: ubuntu-latest # Utiliza un entorno Ubuntu

    steps:
      # Paso 1: Clonar el repositorio para trabajar con los archivos
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Optimizar imágenes usando una acción confiable
      - name: Optimize images
        uses: nwojke/image-actions@v1 # Acción para optimizar imágenes
        with:
          compress_only: true # Solo comprime imágenes sin cambiar su tamaño
          quality: 80 # Establece la calidad en un 80%

      # Paso 3: Confirmar y subir los cambios optimizados automáticamente
      - name: Commit optimized images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Optimized images"
          branch: main

