name: Optimize Images

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en la rama "main"

jobs:
  optimize:
    runs-on: ubuntu-latest  # Usa un entorno basado en Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Descarga el código del repositorio

      - name: Install image optimization tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jpegoptim optipng gifsicle  # Instala herramientas para optimizar imágenes

      - name: Optimize images
        run: |
          find . -type f -name "*.jpg" -exec jpegoptim --max=80 --strip-all {} \;  # Comprime imágenes JPG al 80%
          find . -type f -name "*.png" -exec optipng -o7 {} \;  # Optimiza imágenes PNG
          find . -type f -name "*.gif" -exec gifsicle -O3 --lossy=80 -b {} \;  # Reduce tamaño de GIFs

      - name: Commit optimized images
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .  # Agrega los cambios al repositorio
          git commit -m "Optimized images" || echo "No changes to commit"  # Confirma los cambios si los hay
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/JenniGomez04/WebLaunchV2.git HEAD:main  # Hace push usando el PAT
